/* Developed by Pughal Jeyaprakash */
import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.45.4/+esm";
import { isDemo, supabasePublishableKey, supabaseUrl } from "./supabase-config.js";
export const supabase = isDemo ? null : createClient(supabaseUrl, supabasePublishableKey);
const ADMIN_EMAIL = "admin@campustech.local";
const ALLOWED_IMAGE_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);
const MAX_IMAGE_BYTES = 5 * 1024 * 1024;
const seed=[
 {id:"demo-1",type:"lost",title:"Silver AirPods case",description:"Small silver case with a blue sticker inside the lid.",category:"Electronics",location:"Central Library",item_date:"2026-09-30",status:"open",created_at:"2026-10-02T07:10:00Z",image_url:""},
 {id:"demo-2",type:"found",title:"Blue water bottle",description:"Matte blue bottle left beside the basketball court.",category:"Water Bottles",location:"Sports Complex",item_date:"2026-10-01",status:"open",created_at:"2026-10-02T06:30:00Z",image_url:""},
 {id:"demo-3",type:"lost",title:"Student ID card",description:"Name starts with A. Found near the north gate last seen.",category:"ID & Cards",location:"North Gate",item_date:"2026-09-29",status:"open",created_at:"2026-10-01T15:40:00Z",image_url:""},
 {id:"demo-4",type:"found",title:"Black canvas tote bag",description:"Contains two notebooks and a green highlighter.",category:"Bags",location:"Design Studio",item_date:"2026-09-30",status:"returned",created_at:"2026-10-01T12:20:00Z",image_url:""},
 {id:"demo-5",type:"lost",title:"Brass keyring",description:"Three keys and a tiny orange tag.",category:"Keys",location:"Cafeteria",item_date:"2026-09-28",status:"open",created_at:"2026-09-30T09:00:00Z",image_url:""},
 {id:"demo-6",type:"found",title:"Calculus notebook",description:"Blue graph-paper notebook with handwritten chapter 4 notes.",category:"Books & Stationery",location:"Engineering Block",item_date:"2026-09-27",status:"open",created_at:"2026-09-29T11:00:00Z",image_url:""},
 {id:"demo-7",type:"lost",title:"Grey hoodie",description:"Size M, small stitched campus crest on the sleeve.",category:"Clothing",location:"Auditorium",item_date:"2026-09-26",status:"open",created_at:"2026-09-28T16:00:00Z",image_url:""},
 {id:"demo-8",type:"found",title:"Wallet with cards",description:"Brown wallet handed in at the student office.",category:"Wallets",location:"Student Office",item_date:"2026-09-25",status:"returned",created_at:"2026-09-27T08:00:00Z",image_url:""}
];
let demoItems=structuredClone(seed);let demoUser=null;let blazefacePromise;
export const categories=["Electronics","ID & Cards","Keys","Bags","Books & Stationery","Wallets","Clothing","Water Bottles","Other"];
export async function getSession(){return isDemo?{data:{session:null}}:supabase.auth.getSession()}
export function onAuthChange(cb){return isDemo?{data:{subscription:{unsubscribe(){}}}}:supabase.auth.onAuthStateChange(cb)}
export async function getProfile(userId){if(isDemo)return {data:{is_admin:false},error:null};return supabase.from("profiles").select("is_admin").eq("id",userId).maybeSingle()}
export async function signIn(){if(isDemo){demoUser={id:"demo-user",email:"demo@campus.local",user_metadata:{full_name:"Demo Student"}};return {data:{user:demoUser},error:null}}return supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}${location.pathname}`}})}
export async function signInAdmin(password){if(isDemo)return {data:{user:null},error:new Error("Wrong password")};return supabase.auth.signInWithPassword({email:ADMIN_EMAIL,password})}
export async function signOut(){if(isDemo){demoUser=null;return {error:null}}return supabase.auth.signOut()}
export async function listItems({limit=20,offset=0}={}){if(isDemo)return {data:demoItems.slice(offset,offset+limit),error:null};return supabase.from("items").select("*, item_contacts(contact), returns(*)").order("created_at",{ascending:false}).range(offset,offset+limit-1)}
export async function createItem(item,file,userId){if(isDemo){const next={...item,id:`demo-${Date.now()}`,user_id:userId,created_at:new Date().toISOString(),status:"open",image_url:""};demoItems=[next,...demoItems];return {data:next,error:null}}let imageUrl="";if(file){const blob=await validateAndPrepareImage(file);const path=`${userId}/${Date.now()}-${crypto.randomUUID()}.jpg`;const up=await supabase.storage.from("item-images").upload(path,blob,{contentType:"image/jpeg",upsert:false});if(up.error){console.error("Supabase Storage upload error",up.error);throw up.error;}imageUrl=supabase.storage.from("item-images").getPublicUrl(path).data.publicUrl}const { contact: contactValue, ...itemFields } = item;const {data,error}=await supabase.from("items").insert({...itemFields,user_id:userId,image_url:imageUrl,contact:contactValue}).select().single();return {data,error:error||null}}
export async function createReturn(record){if(isDemo){demoItems=demoItems.map(x=>x.id===record.item_id?{...x,status:"returned",returns:[record]}:x);return {error:null}}return supabase.from("returns").insert(record)}
export async function updateItem(id,fields){if(isDemo){demoItems=demoItems.map(x=>x.id===id?{...x,...fields}:x);return {error:null}}return supabase.from("items").update(fields).eq("id",id)}
export async function deleteItem(id){if(isDemo){demoItems=demoItems.filter(x=>x.id!==id);return {error:null}}return supabase.from("items").delete().eq("id",id)}
export async function reportImage(itemId,reason,reporterId){if(isDemo)return {error:null};return supabase.from("reports").insert({item_id:itemId,reason,reporter_id:reporterId})}
export async function listReports(){if(isDemo)return {data:[],error:null};return supabase.from("reports").select("id,item_id,reason,created_at,items(title,image_url),profiles:reporter_id").order("created_at",{ascending:false})}
async function loadBlazeface(){if(!blazefacePromise)blazefacePromise=import("https://cdn.jsdelivr.net/npm/@tensorflow-models/blazeface@0.0.7/+esm").then(m=>m.load());return blazefacePromise}
export async function validateAndPrepareImage(file){if(!file||!ALLOWED_IMAGE_TYPES.has(file.type))throw new Error("Please choose a JPG, PNG, or WEBP image.");if(file.size>MAX_IMAGE_BYTES)throw new Error("Images must be 5 MB or smaller.");const blob=await compressImage(file);const url=URL.createObjectURL(blob);try{const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Unsupported image."));img.src=url});const model=await loadBlazeface();if((await model.estimateFaces(image,false)).length)throw new Error("This image seems to contain a person. Please upload a photo of the item only.")}finally{URL.revokeObjectURL(url)}return blob}
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("Could not read image."));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("Unsupported image."));img.onload=()=>{const scale=Math.min(1,1024/Math.max(img.width,img.height));const c=document.createElement("canvas");c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext("2d").drawImage(img,0,0,c.width,c.height);let q=.86;const done=()=>c.toBlob(b=>b&&b.size<=MAX_IMAGE_BYTES?resolve(b):(q-=.08,q>.25?done():reject(new Error("Please choose a smaller photo."))),"image/jpeg",q);done()};img.src=reader.result};reader.readAsDataURL(file)})}
export { isDemo };
